name: Build and Sign Android AAB

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradlew Executable
        run: chmod +x gradlew
        continue-on-error: true

      - name: Build AAB
        run: ./gradlew bundleRelease

      - name: Sign AAB File
        run: |
          KEYPATH=$(find . -name "signing.keystore" | head -n 1)
          AABPATH=$(find . -name "app-release.aab" -o -name "*.aab" | head -n 1)
          echo "Keystore dosyasi bulundu: $KEYPATH"
          echo "AAB dosyasi bulundu: $AABPATH"
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore "$KEYPATH" -storepass "mTZ9w0oYnL31" -keypass "mTZ9w0oYnL31" "$AABPATH" my-key-alias

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed-aab
          path: "**/outputs/bundle/release/*.aab"
